name: ciencia-de-dados
channels:
  - conda-forge
dependencies:
  - python=3.8.1
  - pip
  - numpy
  - matplotlib
  - seaborn
  - pandas=1.0.1
  - statsmodels
  - scikit-learn
  - tensorflow=2.0.0
  - rise
  - pip:
    - jupyter-contrib-nbextensions
