name: ciencia-de-dados
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - statsmodels
  - pymc3
  - scikit-learn
  - tensorflow=2.0.0
  - xgboost
  - rise
  - pip:
    - jupyter-contrib-nbextensions
