name: ciencia-de-dados
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - openpyxl
  - scikit-learn
  - rise
  - pip:
    - jupyter-contrib-nbextensions
