name: ciencia-de-dados
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - statsmodels
  - scikit-learn
  - tensorflow
  - rise
  - pip:
    - jupyter-contrib-nbextensions
